host: 127.0.0.1
port: 8081

maxTask: 10

coreTask: 2

# mysql
mysql:
  host: 1.15.123.133
  port: 3306
  user: writer
  pwd: snail2021
  db: snail

zk:
  host: 127.0.0.1
  port: 2181
  root: /Judger
  node: /Judger/node