# 工作路径
workHost: 127.0.0.1
workPort: 8080

# mysql
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  pwd: ccc003
  db: snail

# nsq
nsqProducer:
  host: 127.0.0.1
  port: 4150

nsqConsumer:
  host: 127.0.0.1
  port: 4161
  topic: reset_pwd
  channel: snail_student_reset_backend

# mail
mail:
  account: 348673210@qq.com
  pwd: ysocevomybqmcaai
  host: smtp.qq.com
  port: 465

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  poolSize: 100