# 工作路径
workHost: 127.0.0.1
workPort: 8080

# mysql
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  pwd: root
  db: snail

# nsq
nsqProducer:
  host: 127.0.0.1
  port: 4150

nsqConsumer:
  host: 127.0.0.1
  port: 4161
  topic: reset_pwd
  channel: snail_teacher_reset_backend